version: "3.8"
services:
  backend:
    image: zapoye18/refugio-backend:latest
    container_name: refugio-backend
    environment:
      - NODE_ENV=production
      - PORT=5000
    ports:
      - "5000:5000"
    restart: always

  frontend:
    image: zapoye18/refugio-frontend:latest
    container_name: refugio-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always