name: CI/CD Refugio Animales (EC2, build on server)

on:
  push:
    branches:
      - Pruebas

concurrency:
  group: cicd-refugio-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Descargar el código 
      - name: Checkout código
        uses: actions/checkout@v3

      # Aquí podrías agregar pasos de build local si quisieras validar algo
      - name: Mostrar archivos
        run: ls -lah

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Desplegar en EC2 (build + up)
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e

            # Clonar si no existe
            if [ ! -d "/home/${{ secrets.SERVER_USER }}/refugio" ]; then
              git clone https://github.com/Zapoye18/RTAD_Proyecto_Final /home/${{ secrets.SERVER_USER }}/refugio
            fi
            cd /home/${{ secrets.SERVER_USER }}/refugio

            #Traer últimos cambios de la rama
            git fetch origin
            git checkout Pruebas || git checkout -b Pruebas
            git pull origin Pruebas

            # secretos en .env
            # cat > .env << 'EOF'
            # JWT_SECRET=${{ secrets.JWT_SECRET }}
            # DB_URI=${{ secrets.DB_URI }}
            # EOF

            #Build & Up
            docker compose down
            docker compose build --pull
            docker compose up -d --remove-orphans

            echo "Despliegue OK Definitivo"

