name: CI/CD Refugio Animales (EC2, build on server)

on:
  push:
    branches:
      - Pruebas

concurrency:
  group: cicd-refugio-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Desplegar en EC2 (build + up)
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e

            # Clonar si no existe
            if [ ! -d "/home/${{ secrets.SERVER_USER }}/refugio" ]; then
              git clone https://github.com/Zapoye18/RTAD_Proyecto_Final /home/${{ secrets.SERVER_USER }}/refugio
            fi
            cd /home/${{ secrets.SERVER_USER }}/refugio

            #Traer últimos cambios de la rama
            git fetch origin
            git checkout Testing || git checkout -b Testing
            git pull origin Testing

            # secretos en .env
            # cat > .env << 'EOF'
            # JWT_SECRET=${{ secrets.JWT_SECRET }}
            # DB_URI=${{ secrets.DB_URI }}
            # EOF

            #Build & Up
            docker compose down
            docker compose build --pull
            docker compose up -d --remove-orphans

            #Limpieza de imágenes colgantes
            docker image prune -f

            echo "Despliegue OK"

